AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.13

  Sample SAM Template for LambdaPythonVocationalTest

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  myVocationalTestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64

       # —————— Variables de entorno ——————
      Environment:
        Variables:
          BUCKET_NAME: psychometrictest

      # —————— Permisos S3 GetObject ——————
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - arn:aws:s3:::psychometrictest/*

      # —————— Exponer en API Gateway ——————
      Events:
        GetVocationalTest:
          Type: HttpApi
          Properties:
            Path: /vocational
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.13-v1

Outputs:
  myVocationalTestFunction:
    Description: Hello World second Lambda Function ARN
    Value: !GetAtt myVocationalTestFunction.Arn

  myVocationalTestFunctionIamRole:
    Description: Implicit IAM Role created for Hello World second function
    Value: !GetAtt myVocationalTestFunctionRole.Arn
